
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'LETTERExpr : Expr Expr Expr \n            | Expr Expr\n            | LetterLetter : LETTER'
    
_lr_action_items = {'LETTER':([0,1,2,3,4,5,],[3,3,-3,-4,3,3,]),'$end':([1,2,3,4,5,],[0,-3,-4,-2,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Expr':([0,1,4,5,],[1,4,5,5,]),'Letter':([0,1,4,5,],[2,2,2,2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Expr","S'",1,None,None,None),
  ('Expr -> Expr Expr Expr','Expr',3,'p_grammar','parse.py',7),
  ('Expr -> Expr Expr','Expr',2,'p_grammar','parse.py',8),
  ('Expr -> Letter','Expr',1,'p_grammar','parse.py',9),
  ('Letter -> LETTER','Letter',1,'p_letter','parse.py',18),
]
